### PR TITLE
Suggestion of changes to send server information and event types as lists in config file.

### PR DESCRIPTION
**Pull request by vinialves**
Suggestion of changes to send server information and event types as lists in config file.

This way it is also possible to have comma as part of password.

### CODE REVIEW

**Comment by mraineri** [comment]
Would this be backwards compatible with existing configuration files? If not, I'd like to check with a few others if they're okay updating their config file format.

**Comment by vinialves** [comment]
good point, unfortunately it is not backwards compatible... i can close this PR and in the future when I have opportunity I can try to do it again backwards compatible.. just let me know, thanks

**Comment by mraineri** [comment]
Let's leave the PR open for the time being to bring awareness to the request. I'll see if I can get feedback on this sort of change to see if it'll be okay.

**Comment by mraineri** [comment]
Spoke with some others and we should be okay with updating existing config files. The process is easy to update them.

Approved 10/15

**Pull request merged**
